export const elements = {
  paragraph: "var(--greyish)",
  headline: "var(--blueish)",
  btnText: "var(--whitish)",
  btnBg: "var(--light-blue)",
  tertiary: "var(--red)",
  secondary: "var(--grey-blue)",
  stroke: "var(--blueish)",
  blueishShadow: "var(--blueish-shadow)",
  lightBlueShadow: "var(--light-blue-shadow)",
  greyBlueShadow: "var(--grey-blue-shadow)",
  background: "var(--background)",
  danger: "var(--danger)",
}
export const elevations = {
  shadowXs: "var(--sh-xs)",
  shadowS: "var(--sh-s)",
  shadowSh: "var(--sh)",
  shadowM: "var(--sh-m)",
  shadowL: "var(--sh-l)",
  shadowLg: "var(--sh-lg)",
  shadowXl: "var(--sh-xl)",
  shadowInner: "var(--sh-inner)",
  shadowOutline: "var(--sh-outline)",
}
