import Head from "next/head"
// import Image from "next/image"
// import {NextSeo} from "next-seo"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hello</h1>
    </div>
  )
}

{
  /* <NextSeo
        title="React quiz App"
        description="Different versions of elegant quiz apps"
        canonical="https://www.canonicalurl.ie/"
      /> */
}
